const featuresData = [
  {
    id: 1,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "BitAgent",
    description: "Vigilant in monitoring agent activity for anomalies.",
    link: "https://bitagent.com",
  },
  {
    id: 2,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "StoryAgents",
    description: "Sharing their creation stories, from niche domains to legal chains.",
    link: "https://storyagents.com",
  },
  {
    id: 3,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ServerAgents",
    description: "Setting up shop in Cloudflare and monitoring sync.",
    link: "https://serveragents.com",
  },
  {
    id: 4,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "HashAgent",
    description: "Crafting meta hashes, finding, storing, indexing, analyzing, and optimizing for SEO.",
    link: "https://hashagent.com",
  },
  {
    id: 5,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SocialAgent",
    description: "Gathering social insights, orchestrating social handle takeovers, and publishing to accounts.",
    link: "https://socialagent.com",
  },
  {
    id: 6,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CodeAgent",
    description: "Proficient in pulling from Git repositories and publishing to five code creation systems.",
    link: "https://codeagent.com",
  },
  {
    id: 7,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PersonnelAgent",
    description: "Understanding human needs based on identity and engagement skills.",
    link: "https://personnelagent.com",
  },
  {
    id: 8,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ContentAgent",
    description: "Masters of creating meta, articles, and more.",
    link: "https://contentagent.com",
  },
  {
    id: 9,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "AdvoAgent",
    description: "Experts in PPC, securing exact match keywords, and strategic buying.",
    link: "https://advoagent.com",
  },
  {
    id: 10,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "GovAgent",
    description: "Efficiently handling efiling, abot, utility, and equity enforcement.",
    link: "https://govagent.com",
  },
  {
    id: 11,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "NetworkAgent",
    description: "The go-to for sales strategies and networking using Contrib Network and VNOC.",
    link: "https://networkagent.com",
  },
  {
    id: 12,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "UtilityAgent",
    description: "Experts in sourcing agents and output needs.",
    link: "https://utilityagent.com",
  },
  {
    id: 13,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "LinkAgent",
    description: "Masters of API management, hash optimization, and URL perfection.",
    link: "https://linkagent.com",
  },
  {
    id: 14,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CapitalAgent",
    description: "Creating wallets, Dex accounts, multi-signatures, and managing eservices payouts.",
    link: "https://capitalagent.com",
  },
  {
    id: 15,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SecurityAgent",
    description: "Keeping a vigilant eye on anomalies and suspicious activity.",
    link: "https://securityagent.com",
  },
  {
    id: 16,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "LiveAgent",
    description: "Ready to engage and assist when needed.",
    link: "https://liveagent.com",
  },
  {
    id: 17,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SupportAgent",
    description: "Providing assistance and support to users in real-time.",
    link: "https://supportagent.com",
  },
  {
    id: 18,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "StatsAgent",
    description: "Crunching the numbers for in-depth analytics.",
    link: "https://statsagent.com",
  },
  {
    id: 19,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PortfolioAgent",
    description: "Leveraging new assets for portfolio leverage and resource extraction.",
    link: "https://portfolioagent.com",
  },
  {
    id: 20,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PitchAgent",
    description: "Crafting engaging sales and story documents.",
    link: "https://pitchagent.com",
  },
  {
    id: 21,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TestAgent",
    description: "Ensuring all systems work flawlessly and finding any missing agent deliverables.",
    link: "https://testagent.com",
  },
  {
    id: 22,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "GrowAgent",
    description: "Focused on macro analysis to accelerate asset growth with limited resources.",
    link: "https://growagent.com",
  },
  {
    id: 23,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "FundAgent",
    description: "Exploring DeFi, Dex, Gnosis multi-signature, and compound bonding curve for eshares.",
    link: "https://fundagent.com",
  },
  {
    id: 24,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ReferAgent",
    description: "Powered by referrals.com, gathering the first 10 customers.",
    link: "https://referagent.com",
  },
  {
    id: 25,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PartnerAgent",
    description: "Investigating partner strategies to engage and align with.",
    link: "https://partneragent.com",
  },
  {
    id: 26,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "AttackAgent",
    description: "Specializes in cybersecurity, protecting networks from unauthorized access and cyber threats.",
    link: "https://attackagent.com",
  },
  {
    id: 27,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "BankAgent",
    description: "Provides secure and efficient banking services, including transaction processing and fraud detection.",
    link: "https://bankagent.com",
  },
  {
    id: 28,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "BillAgent",
    description: "Automates and manages billing processes, ensuring accuracy and efficiency in financial transactions.",
    link: "https://billagent.com",
  },
  {
    id: 29,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CareAgent",
    description: "Delivers personalized healthcare services, utilizing AI to tailor care plans and monitor patient health.",
    link: "https://careagent.com",
  },
  {
    id: 30,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "DealAgent",
    description: "Automates deal-making processes, from negotiation to closure, ensuring optimal terms and efficiency.",
    link: "https://dealagent.com",
  },
  {
    id: 31,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "EquityAgent",
    description: "Analyzes and manages equity investments, providing market insights and financial advice to maximize returns.",
    link: "https://equityagent.com",
  },
  {
    id: 32,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "GamingAgent",
    description: "Enhances gaming experiences by integrating advanced AI to provide personalized gaming suggestions and optimizations.",
    link: "https://gamingagent.com",
  },
  {
    id: 33,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "GridAgent",
    description: "Optimizes power grid operations through real-time analytics and smart distribution strategies.",
    link: "https://gridagent.com",
  },
  {
    id: 34,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "IpAgent",
    description: "Manages and protects intellectual property rights, supporting innovation and compliance.",
    link: "https://ipagent.com",
  },
  {
    id: 35,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "MobileAgent",
    description: "Focuses on mobile optimizations and solutions, ensuring seamless mobile experiences across various platforms.",
    link: "https://mobileagent.com",
  },
  {
    id: 36,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PollAgent",
    description: "Conducts and analyzes polls and surveys, providing insights into public opinion and market trends.",
    link: "https://pollagent.com",
  },
  {
    id: 37,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ScienceAgent",
    description: "Facilitates scientific research by providing tools for data analysis, experiment tracking, and resource management.",
    link: "https://scienceagent.com",
  },
  {
    id: 38,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SupplyAgent",
    description: "Manages supply chain logistics, employing advanced algorithms to streamline operations and reduce costs.",
    link: "https://supplyagent.com",
  },
  {
    id: 39,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "VoiceAgent",
    description: "Offers voice recognition and processing capabilities to enhance user interaction with devices through natural language.",
    link: "https://voiceagent.com",
  },
  {
    id: 40,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "AgentChallenge",
    description: "Creates challenges for AI agents.",
    link: "https://agentchallenge.com",
  },
  {
    id: 41,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "AgentNews",
    description: "Builds news sites using AI agents.",
    link: "https://agentnews.com",
  },
  {
    id: 42,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "AgentManager",
    description: "Manages agents for your domain.",
    link: "https://agentmanager.com",
  },
  {
    id: 43,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "FinanceAgent",
    description: "Automates financial analysis and investment strategies.",
    link: "https://financeagent.com",
  },
  {
    id: 44,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CryptoAgent",
    description: "Manages cryptocurrency investments and trading.",
    link: "https://cryptoagent.com",
  },
  {
    id: 45,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "Abot",
    description: "Offers AI-powered automation tools to streamline business processes.",
    link: "https://abot.com",
  },
  {
    id: 46,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "AccountBot",
    description: "Streamlines financial management by automating bookkeeping, reporting, and account reconciliation.",
    link: "https://accountbot.com",
  },
  {
    id: 47,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "BotChallenge",
    description: "Hosts competitions and challenges for AI and robotics enthusiasts.",
    link: "https://botchallenge.com",
  },
  {
    id: 48,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "BusinessBot",
    description: "Automates business processes, enabling companies to operate more efficiently.",
    link: "https://businessbot.com",
  },
  {
    id: 49,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CampusBot",
    description: "Offers AI-driven tools for student engagement, campus management, and academic support.",
    link: "https://campusbot.com",
  },
  {
    id: 50,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CarbonAgents",
    description: "Supports sustainability efforts by providing tools and resources for carbon footprint management.",
    link: "https://carbonagents.com",
  },
  {
    id: 51,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CarbonBots",
    description: "Empowers businesses to manage and reduce their carbon footprint with AI-driven tools.",
    link: "https://carbonbots.com",
  },
  {
    id: 52,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CasinoBot",
    description: "Provides AI-powered solutions for the gaming and casino industry.",
    link: "https://casinobot.com",
  },
  {
    id: 53,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ChallengeAgent",
    description: "Facilitates innovation by connecting organizations with problem solvers.",
    link: "https://challengeagent.com",
  },
  {
    id: 54,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CorpBot",
    description: "Streamlines corporate operations with AI-driven solutions for workflow automation and document management.",
    link: "https://corpbots.com",
  },
  {
    id: 55,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CourtAgent",
    description: "Simplifies legal processes by providing AI-assisted tools for case management.",
    link: "https://courtagent.com",
  },
  {
    id: 56,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CruiseAgent",
    description: "Connects travelers with personalized cruise experiences.",
    link: "https://cruiseagent.com",
  },
  {
    id: 57,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CyberBot",
    description: "Offers advanced cybersecurity solutions powered by AI.",
    link: "https://cyberbot.com",
  },
  {
    id: 58,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "CyberBots",
    description: "Offers advanced cybersecurity solutions powered by AI.",
    link: "https://cyberbots.com",
  },
  {
    id: 59,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "DebtAgent",
    description: "Provides debt management solutions.",
    link: "https://debtagent.com",
  },
  {
    id: 60,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "DesignBots",
    description: "Automates the design process, offering AI-powered tools for graphic design.",
    link: "https://designbots.com",
  },
  {
    id: 61,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "DockerAgent",
    description: "Specializes in containerization services, helping businesses deploy and manage applications.",
    link: "https://dockeragent.com",
  },
  {
    id: 62,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "EduAgent",
    description: "Connects students with educational resources and opportunities.",
    link: "https://eduagent.com",
  },
  {
    id: 63,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "EnergyBots",
    description: "Offers AI-driven energy management solutions.",
    link: "https://energybots.com",
  },
  {
    id: 64,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "FantasyBot",
    description: "Enhances fantasy sports experiences with AI-powered tools for team management.",
    link: "https://fantasybot.com",
  },
  {
    id: 65,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "GrantAgent",
    description: "Connects organizations with grant opportunities.",
    link: "https://grantagent.com",
  },
  {
    id: 66,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "HealthAgent",
    description: "Revolutionizes healthcare by connecting users with AI-driven tools for personalized health management.",
    link: "https://healthagent.com",
  },
  {
    id: 67,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "HealthAgents",
    description: "Connects users with personalized healthcare services.",
    link: "https://healthagents.com",
  },
  {
    id: 68,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "HistoryBot",
    description: "Provides educational tools and resources focused on history.",
    link: "https://historybot.com",
  },
  {
    id: 69,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "HomeBot",
    description: "Offers smart home automation solutions.",
    link: "https://homebot.com",
  },
  {
    id: 70,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "IBot",
    description: "Provides AI-powered solutions for personal and business productivity.",
    link: "https://ibot.com",
  },
  {
    id: 71,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "IPAgent",
    description: "Specializes in intellectual property management.",
    link: "https://ipagent.com",
  },
  {
    id: 72,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "JavaBot",
    description: "Offers Java development services.",
    link: "https://javabot.com",
  },
  {
    id: 73,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "LawyerBot",
    description: "Simplifies legal services by offering AI-driven tools for document preparation.",
    link: "https://lawyerbot.com",
  },
  {
    id: 74,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "LeaseAgent",
    description: "Provides tools for managing lease agreements.",
    link: "https://leaseagent.com",
  },
  {
    id: 75,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "LiveAgents",
    description: "Connects businesses with live customer service agents.",
    link: "https://liveagents.com",
  },
  {
    id: 76,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "LoanBots",
    description: "Automates loan processing with AI-powered tools.",
    link: "https://loanbots.com",
  },
  {
    id: 77,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "MarketBot",
    description: "Provides AI-driven marketing solutions.",
    link: "https://marketbot.com",
  },
  {
    id: 78,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "MediaBot",
    description: "Automates media production and distribution with AI-powered tools.",
    link: "https://mediabot.com",
  },
  {
    id: 79,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "MedicalAgent",
    description: "Connects users with healthcare services.",
    link: "https://medicalagent.com",
  },
  {
    id: 80,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "NodeAgent",
    description: "Specializes in node management and deployment services.",
    link: "https://nodeagent.com",
  },
  {
    id: 81,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "NutriAgent",
    description: "Provides personalized nutrition and wellness advice.",
    link: "https://nutriagent.com",
  },
  {
    id: 82,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "OceanBot",
    description: "Offers ocean exploration and conservation tools.",
    link: "https://oceanbot.com",
  },
  {
    id: 83,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PartyAgent",
    description: "Offers event planning and management services.",
    link: "https://partyagent.com",
  },
  {
    id: 84,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PartyBot",
    description: "Automates party planning with AI-powered tools.",
    link: "https://partybots.com",
  },
  {
    id: 85,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PeaceBot",
    description: "Promotes global peace initiatives with AI-driven tools.",
    link: "https://peacebot.com",
  },
  {
    id: 86,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PictureBot",
    description: "Automates image editing and management.",
    link: "https://picturebot.com",
  },
  {
    id: 87,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PlayAgents",
    description: "Connects gamers with opportunities in the gaming industry.",
    link: "https://playagents.com",
  },
  {
    id: 88,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PoliticalAgent",
    description: "Offers campaign management solutions for political strategies.",
    link: "https://politicalagent.com",
  },
  {
    id: 89,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PollutionBot",
    description: "Monitors and reports on environmental pollution with AI-powered tools.",
    link: "https://pollutionbot.com",
  },
  {
    id: 90,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PornAgent",
    description: "Provides a secure and personalized platform for adult content.",
    link: "https://pornagent.com",
  },
  {
    id: 91,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PRAgent",
    description: "Offers public relations services with AI-driven tools.",
    link: "https://pragent.com",
  },
  {
    id: 92,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ProductBot",
    description: "Automates product management with AI-powered tools.",
    link: "https://productbot.com",
  },
  {
    id: 93,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ProfileAgent",
    description: "Helps individuals and businesses manage their online profiles.",
    link: "https://profileagent.com",
  },
  {
    id: 94,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ProfileBot",
    description: "Automates profile management across platforms.",
    link: "https://profilebot.com",
  },
  {
    id: 95,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PropertyBot",
    description: "Offers real estate management solutions with AI-driven tools.",
    link: "https://propertybot.com",
  },
  {
    id: 96,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "PurchaseAgent",
    description: "Automates the purchasing process.",
    link: "https://purchaseagent.com",
  },
  {
    id: 97,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "RealtorAgent",
    description: "Connects real estate agents with clients.",
    link: "https://realtoragent.com",
  },
  {
    id: 98,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "RealtyBot",
    description: "Automates real estate transactions.",
    link: "https://realtybot.com",
  },
  {
    id: 99,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SchoolBot",
    description: "Offers AI-driven solutions for educational institutions.",
    link: "https://schoolbot.com",
  },
  {
    id: 100,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SecurityBot",
    description: "Specializes in cybersecurity automation.",
    link: "https://securitybot.com",
  },
  {
    id: 101,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SeedAgent",
    description: "Helps startups secure seed funding.",
    link: "https://seedagent.com",
  },
  {
    id: 102,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ServerAgents",
    description: "Offers server management and optimization services.",
    link: "https://serveragents.com",
  },
  {
    id: 103,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ServiceAgents",
    description: "Connects businesses with service providers.",
    link: "https://serviceagents.com",
  },
  {
    id: 104,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "ServiceBot",
    description: "Automates customer service with AI-powered tools.",
    link: "https://servicebot.com",
  },
  {
    id: 105,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SexBots",
    description: "Offers AI-driven companionship solutions.",
    link: "https://sexbots.com",
  },
  {
    id: 106,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SoftwareBot",
    description: "Automates software development processes.",
    link: "https://softwarebot.com",
  },
  {
    id: 107,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "SportsBot",
    description: "Provides AI-powered sports analytics.",
    link: "https://sportsbot.com",
  },
  {
    id: 108,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "StoreBot",
    description: "Automates e-commerce operations with AI-driven tools.",
    link: "https://storebot.com",
  },
  {
    id: 109,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "StreamAgent",
    description: "Enhances live streaming experiences with AI-driven tools.",
    link: "https://streamagent.com",
  },
  {
    id: 110,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "StudentAgent",
    description: "Connects students with educational opportunities.",
    link: "https://studentagent.com",
  },
  {
    id: 111,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "StyleBot",
    description: "Offers personalized fashion advice and styling services.",
    link: "https://stylebot.com",
  },
  {
    id: 112,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TalkBot",
    description: "Offers AI-powered conversational agents.",
    link: "https://talkbot.com",
  },
  {
    id: 113,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TechBot",
    description: "Automates IT support and management with AI-driven tools.",
    link: "https://techbot.com",
  },
  {
    id: 114,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TicketBot",
    description: "Automates ticket sales and management.",
    link: "https://ticketbot.com",
  },
  {
    id: 115,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TitleBot",
    description: "Simplifies title management in real estate transactions.",
    link: "https://titlebot.com",
  },
  {
    id: 116,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TourBot",
    description: "Offers virtual tour solutions for real estate and travel.",
    link: "https://tourbot.com",
  },
  {
    id: 117,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TradeBots",
    description: "Automates trading strategies with AI-powered tools.",
    link: "https://tradebots.com",
  },
  {
    id: 118,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "TradingBot",
    description: "Delivers automated trading solutions with AI-driven tools.",
    link: "https://tradingbot.com",
  },
  {
    id: 119,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "VBot",
    description: "Offers versatile AI-powered virtual assistants.",
    link: "https://vbot.com",
  },
  {
    id: 120,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "VendorBot",
    description: "Streamlines vendor management with AI-driven tools.",
    link: "https://vendorbot.com",
  },
  {
    id: 121,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "VentureBot",
    description: "Provides AI-powered tools for venture capital and startup management.",
    link: "https://venturebot.com",
  },
  {
    id: 122,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "VetBot",
    description: "Offers veterinary services and pet care advice.",
    link: "https://vetbot.com",
  },
  {
    id: 123,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "VirtualBot",
    description: "Creates virtual assistants and AI-driven solutions.",
    link: "https://virtualbot.com",
  },
  {
    id: 124,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "WellnessAgent",
    description: "Promotes health and wellness by offering personalized wellness plans and telehealth services.",
    link: "https://wellnessagent.com",
  },
  {
    id: 125,
    icon: "https://cdn.vnoc.com/icons/agentdao-common-icon.webp",
    image: "",
    title: "WidgetAgent",
    description: "Develops custom widgets for integration across platforms.",
    link: "https://widgetagent.com",
  }
];

// Sort the featuresData array alphabetically by title
featuresData.sort((a, b) => a.title.localeCompare(b.title));

export default featuresData;
